apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookshelf
spec:
  ingressClassName: traefik
  rules:
    - host: localhost\bookshelf
      http:
        paths:
          - backend:
              service:
                name: bookshelf
                port:
                  number: 3005
            path: /
            pathType: Prefix
