apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookshelf-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: bookshelfland.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bookshelf
            port:
              number: 3005
