apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshelf2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookshelf2

  template:
    metadata:
      labels:
        app: bookshelf2

    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000

      containers:
        - name: bookshelf2
          image: ghcr.io/advplyr/audiobookshelf:2.30.0

          envFrom:
            - configMapRef:
                name: bookshelf2-configmap

          ports:
            - containerPort: 3005
              protocol: TCP

          volumeMounts:
            - mountPath: /config
              name: audiobookshelf-config
            - mountPath: /metadata
              name: audiobookshelf-metadata
            - mountPath: /audiobooks
              name: audiobookshelf-audiobooks

      restartPolicy: Always

      volumes:
        - name: audiobookshelf-config
          persistentVolumeClaim:
            claimName: audiobookshelf-config
        - name: audiobookshelf-metadata
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata
        - name: audiobookshelf-audiobooks
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks
