apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshelf2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookshelf2
  template:
    metadata:
      labels:
        app: bookshelf2
    spec:

      containers:
        - name: bookshelf2
          image: ghcr.io/advplyr/audiobookshelf:latest
          ports:
            - containerPort: 80

          volumeMounts:
            - name: data
              mountPath: /audiobooks
              subPath: audiobooks
            - name: data
              mountPath: /podcasts
              subPath: podcasts
            - name: data
              mountPath: /config
              subPath: config
            - name: data
              mountPath: /metadata
              subPath: metadata
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bookshelf-data

