apiVersion: v1
kind: Service
metadata:
  name: bookshelf2-service
spec:
  type: ClusterIP  # This is the default service type
  selector:
    app: bookshelf2 # Must match the pod's label
  ports:
    - protocol: TCP
      port: 3005      # The service port for internal cluster access
      targetPort: 3005  # The port on the pod/container
