apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookshelf
  template:
    metadata:
      labels:
        app: bookshelf
    spec:
      securityContext:
        fsGroup: 33 # www-data group ID
        runAsUser: 33 # www-data user ID
        runAsGroup: 33 # www-data group ID

      containers:
        - name: bookshelf
          image: ghcr.io/advplyr/audiobookshelf:latest
          ports:
            - containerPort: 3005

          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: metadata-volume
              mountPath: /metadata
            - name: audiobooks-volume
              mountPath: /audiobooks
            - name: podcasts-volume
              mountPath: /podcasts-volume
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: audiobookshelf-config-pvc
        - name: metadata-volume
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata-pvc
        - name: audiobooks-volume
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks-pvc
        - name: podcasts-volume
          persistentVolumeClaim:
            claimName: audiobookshelf-podcasts-pvc
