apiVersion: v1
kind: Service
metadata:
  name: bookshelf
  labels:
    app: bookshelf
spec:
  selector:
    app: bookshelf
  ports:
    - name: http
      protocol: TCP
      port: 80        # Service port (used by clients inside the cluster)
      targetPort: 3005  # Container port defined in Deployment
  type: ClusterIP
