apiVersion: v1
kind: Service
metadata:
  name: bookshelf
  labels:
    app: bookshelf
spec:
  type: ClusterIP
  selector:
    app: bookshelf
  ports:
    - name: http
      protocol: TCP
      port: 80        # Port that other pods in the cluster will use
      targetPort: 3005  # Port exposed by the container in your Deployment

