apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-pvc
spec:
  accessModes:
    - ReadWriteOnce # Or ReadWriteMany if your storage supports it
  resources:
    requests:
      storage: 1Gi # Adjust size as needed
  storageClassName: my-audiobookshelf-storage # Or omit to use default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: my-audiobookshelf-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-audiobooks-pvc
spec:
  accessModes:
    - ReadWriteMany # Recommended for media if multiple pods might access it
  resources:
    requests:
      storage: 1Gi # Adjust based on your collection size
  storageClassName: my-audiobookshelf-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-podcasts-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: my-audiobookshelf-storage
