apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-pvc
spec:
  accessModes:
    - ReadWriteOnce # Or ReadWriteMany if your storage supports it
  resources:
    requests:
      storage: 1Gi # Adjust size as needed
  storageClassName: my-audiobookshelf-storage # Or omit to use default
